### ISSUE TITLE
GeoChemistryPy.plot.map_plot.map_projected()

### ISSUE THREAD

**Issue by SanyHe** [ZJUEarthData/geochemistrypy#5]
Bulid a function of projecting data points in the world map from the selected column.

Interface of the function: **def map_projected(col, df):**
:param col: pd.Series, one selected column from the data sheet
:param df: pd.DataFrame, the data sheet

Attention: 
+ you can use **save_figure** (a built-in function) to save the produced figure.

**Comment by 3180101673** [comment]
def map1(path,value,lon,lat):
    #path为文件路径
    #value为属性值字段名
    #lon为纬度字段名
    #lat为经度字段名

    import pandas as pd
    import geopandas
    import matplotlib.pyplot as plt
    from mpl_toolkits.axes_grid1 import make_axes_locatable

    df1 = pd.read_excel(path)

    # Keep only relevant columns
    df = df1.loc[:, ( value, lon, lat)]
    

    # Create point geometries
    geometry = geopandas.points_from_xy(df.lon, df.lat)
    geo_df = geopandas.GeoDataFrame(df[[ value, lon, lat]], geometry=geometry)

    world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))

    fig, ax = plt.subplots(figsize=(24,18))

    divider = make_axes_locatable(ax)


    cax = divider.append_axes("right", size="5%", pad=0.1)


    world.plot(ax=ax, alpha=0.4,color = 'grey',edgecolor='black')
    geo_df.plot(value, ax=ax,s=20,cmap='gist_heat_r',cax=cax,legend=True)
    
    #'hot;
    #scheme颜色映射方式，需要pip install mapclassify
    plt.title('counts')
    plt.savefig("sample distribution.jpg")
    plt.show()

**Comment by 3180101673** [comment]
map1(path='/Users/mac/Desktop/Geochemistry/paper/test1.xlsx',value='NA2O(WT%)', lon='lon', lat='lat' )

**Comment by 3180101673** [comment]
[test1.xlsx](https://github.com/ZJUEarthData/geochemistrypy/files/8140794/test1.xlsx)
